# Vibrant "Cyberpunk" Neon Colors (Dark Mode)

[colors]
name = "Surge Cyberpunk"
is_dark = true

[colors.primary]
# base 00 - DarkGray.dark
background = '#282a36'
# base 05 - White(Standard Text)
foreground = '#f8f8f2'

[colors.normal]
# base 01 - Gray(Selection/Borders)
black =   '#44475a'
# base 08 - StateError
red =     '#ff5555'
# base 0B - StateDownloading
green =   '#50fa7b'
# base 0A - StatePaused
yellow =  '#ffb86c'
# base 0D - Blue (Version)
blue =    '#58a6ff'
# base 0E - Magenta (or StateDone)
magenta = '#bd93f9'
# base 0C - Cyan
cyan =    '#8be9fd' 
# base 07 - White
white =   '#f8f8f2'

[colors.bright]
# base 03 - LightGray (Comments/Secondary Info)
black =   '#a9b1d6'
# base 09 - ProgressStart(Neon Pink)
red =     '#ff79c6'
# base 0B - StateDownloading.dark
green =   '#50fa7b'
# base 0A - StatePaused.dark
yellow =  '#ffb86c'
# base 0D - Blue (Version)
blue =    '#58a6ff'
# base 0F - ProgressEnd(Neon Purple)
magenta = '#bd93f9'
# base 0C - Cyan
cyan =    '#8be9fd' 
# base 07 - White
white =   '#f8f8f2'
